### ISSUE TITLE
Rename the project to something more sensible?

### ISSUE THREAD

**Issue by fuerbringer** [Hoi15A/EksDeeBot#7]
`Telegram-Bot` is extremely vague and doesn't really tell us anything about the project. Here are my suggestions for new names:

1. Austin-Bot
2. Randomizer-Bot
3. Ro-Bot (_as in Robot like in /r9k/_)
Picking one depends on which ones are already registered with Botfather. More suggestions welcome.
@Hoi15A @GianlucaScarciolla

**Comment by Hoi15A** [comment]
Repo has been renamed, bot will soon follow.
